# Generated by Django 4.0.1 on 2022-01-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_project_projecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projecto',
            new_name='Project',
        ),
    ]
